version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=./data/uasset.db
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./env.example:/usr/src/app/env.example
      - data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  data: 